# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Your own specialized rules go here

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-i18n
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/**/*.rb"

Layout/LineLength:
  Exclude:
    - "config/**/*.rb"

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false
I18n/RailsI18n/DecorateString:
  Exclude:
    - "db/seeds.rb"
    - "db/seeds/development.rb"
    - "spec/rails_helper.rb"
    - "app/services/**/*.rb"
