name: Ruby CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        # ruby-version: '3.3'
        # Not needed with a .ruby-version file
        bundler-cache: true
        # runs 'bundle install' and caches installed gems automatically

    - name: Setup Database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      run: bundle exec rails db:setup

    - name: Run Tests
      run: bundle exec rspec
